<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '';
echo '<!-- Basic Page Needs';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<meta charset="utf-8">';
echo '<title>tacticus.digital | citius | altius | fortius</title>';
echo '<meta name="description" content="tacticus is an initative to provide top-notch solutions on strategic marketing, content creation, marketing analytics, seo, digital ads, and ux research.">';
echo '<meta name="author" content="A. B. Gökhan">';
echo '<meta name="robots" content="max-image-preview:large" />';
echo '<link rel="canonical" href="https://tacticus.digital/" />';
echo '<meta property="og:locale" content="en_US" />';
echo '<meta property="og:locale:alternate" content="en_GB" />';
echo '<meta property="og:locale:alternate" content="tr_TR" />';
echo '<meta property="og:site_name" content="tacticus.digital" />';
echo '<meta property="og:type" content="website" />';
echo '<meta property="og:title" content="tacticus.digital | citius | altius | fortius" />';
echo '<meta property="og:description" content="tacticus is an initative to provide top-notch solutions on strategic marketing, content creation, marketing analytics, seo, digital ads, and ux research." />';
echo '<meta property="og:url" content="https://tacticus.digital/" />';
echo '<meta name="twitter:card" content="summary" />';
echo '<meta name="twitter:title" content="tacticus.digital | citius | altius | fortius" />';
echo '<meta name="twitter:description" content="tacticus is an initative to provide top-notch solutions on strategic marketing, content creation, marketing analytics, seo, digital ads, and ux research." />';
echo '';
echo '<!-- Mobile Specific Metas';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<!-- FONT';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">';
echo '';
echo '<!-- CSS';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<link rel="stylesheet" href="css/normalize.css">';
echo '<link rel="stylesheet" href="css/skeleton.css">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link rel="stylesheet" href="css/fancybox.css">';
echo '<link rel="stylesheet" href="css/font-awesome.css">';
echo '';
echo '<!-- Javascript';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<script type="text/javascript" src="js/jquery-3.6.0.min.js"></script>';
echo '<script type="text/javascript" src="js/isotope.pkgd.min.js"></script>';
echo '<script type="text/javascript" src="js/scrollreveal.min.js"></script>';
echo '<script type="text/javascript" src="js/jquery.singlePageNav.min.js"></script>';
echo '<script type="text/javascript" src="js/fancybox.umd.js"></script>';
echo '<script type="text/javascript" src="js/scripts.js"></script>';
echo '';
echo '<!-- Favicon';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<link rel="icon" type="image/png" href="images/favicon.png">';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Primary Page Layout';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<!-- Menu';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '<nav class="navigation">';
echo '<a href="#" class="menu-icon">';
echo '<i class="fa fa-bars"></i>';
echo '</a>';
echo '<ul class="main-navigation" role="navigation">';
echo '<li><a href="#hero">Home</a></li>';
echo '<li><a href="#introduction">Introduction</a></li>';
echo '<li><a href="#creativity">Creativity</a></li>';
echo '<li><a href="#work">Work</a></li>';
echo '<li><a href="#help">Help</a></li>';
echo '<li><a href="#clients">Clients</a></li>';
echo '<li><a href="#about">About</a></li>';
echo '<li><a href="#why-us">Why us?</a></li>';
echo '<li><a href="#quote">Quote</a></li>';
echo '<li><a href="#contact">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '';
echo '<!-- Hero';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="hero" class="hero u-full-width">';
echo '<div class="hero-image"></div>';
echo '<div class="container centered">';
echo '<div class="twelve columns">';
echo '<h1 class="separator">Tacticus 2</h1>';
echo '<h2>Citius, Altius, Fortius.</h2>';
echo '<h2>"Faster, Higher, Stronger."</h2>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Introduction';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="introduction" class="introduction u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="twelve columns">';
echo '<h3 class="separator">Introduction</h3>';
echo '<h4>We provide solutions for your digital marketing strategy in order to make your users to reach your brand faster, to get your product higher on search engines, and to help you to stand stronger among competitors.</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Creativity';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="creativity" class="creativity u-full-width featured-bg-image">';
echo '<h4 class="centered">';
echo '<button class="button inverted">Creativity on purpose.</button>';
echo '</h4>';
echo '</section>';
echo '';
echo '<!-- Work';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="work" class="work u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="twelve columns">';
echo '<h3 class="separator">Some of our work</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<!-- work filters -->';
echo '<ul class="work-filters u-full-width">';
echo '<li class="active">';
echo '<a href="#">All</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">Strategic Marketing</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">Content Creation</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">Marketing Analytics</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">SEO</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">Digital Ads</a>';
echo '</li>';
echo '<li>';
echo '<a href="#">UX Reseach</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="row">';
echo '<!-- work items -->';
echo '<ul class="work-items u-cf">';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port1.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>1</h3>';
echo '<p class="separator orange">Strategic Marketing</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port2.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>2</h3>';
echo '<p class="separator orange">Content Creation</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port3.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>3</h3>';
echo '<p class="separator orange">Marketing Analytics</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port4.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>4</h3>';
echo '<p class="separator orange">SEO</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port5.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>5</h3>';
echo '<p class="separator orange">Digital Ads</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="four columns">';
echo '<img src="images/portfolio/port6.svg">';
echo '<div class="work-detail">';
echo '<div class="vertical-centered">';
echo '<h3>1</h3>';
echo '<p class="separator orange">UX Research</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Help';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="help" class="help u-full-width featured-bg-image">';
echo '<h4 class="centered">';
echo '<button class="button inverted">We’re here to help!</button>';
echo '</h4>';
echo '</section>';
echo '';
echo '<!-- Clients';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="clients" class="clients u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<h3 class="separator">Our client portfolio</h3>';
echo '</div>';
echo '<ul class="clients u-full-width u-cf">';
echo '<li>';
echo 'SMEs';
echo '</li>';
echo '<li>';
echo 'Start-ups';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- About';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="about" class="about u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<!-- introduction -->';
echo '<div class="twelve columns">';
echo '<h3 class="separator">About us</h3>';
echo '<h4>Tacticus is an initiative by Burak Gokhan, to provide top-notch digital marketing solutions.</h4>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<!-- people list -->';
echo '<ul class="people-list">';
echo '<li class="three columns people-list-item">';
echo '<img src="images/burak-gokhan-portrait.webp">';
echo '<div class="people-hover">';
echo '<a href="https://www.linkedin.com/in/abgokhan/" target="_blank"><i class="fa fa-external-link"></i></a>';
echo '<div class="people-detail">';
echo '<h3>Burak Gokhan</h3>';
echo '<p>Digital Marketing Analyst/Founder</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Why Us?';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="why-us" class="why u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<!-- introduction section -->';
echo '<div class="twelve columns">';
echo '<h3 class="separator">Why choose us</h3>';
echo '<h4>Competiton is a reality, and our services are designed to help you among other competitiors.</h4>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<!-- services section -->';
echo '<ul class="services">';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/strategic-marketing.webp">';
echo '</div>';
echo '<h5>Strategic Marketing</h5>';
echo '<p>A marketing strategy can help an organization focus its resources on the best opportunities to increase sales and gain a competitive advantage. Before strategizing, a company must analyze its strategic position before it can formulate, evaluate and select a market-oriented competitive position that will help them achieve their marketing goals. The study of strategic marketing is a separate field and was developed from the earlier areas of strategic management. Marketing strategy emphasizes the importance of marketing as a link between an organization and its customers. Marketing strategy combines the resources and capabilities of an organization to gain a competitive advantage that enhances firm performance.</p>';
echo '</li>';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/marketing-analytics.webp">';
echo '</div>';
echo '<h5>Marketing Analytics</h5>';
echo '<p>Marketing analytics refers to the process of measuring, managing, and analysing marketing performance in order to maximize effectiveness and optimize return-on-investment (ROI). Marketing analytics can help marketers be more efficient and reduce wasted marketing dollars by understanding how they work. Marketing analytics provides insight into customer preferences and trends that can be used to generate leads and sales. These compelling benefits aside, most organizations don't realize the potential of marketing analytics because they aren't able to measure ROI.</p>';
echo '</li>';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/search-engine-optimization.webp">';
echo '</div>';
echo '<h5>Search Engine Optimisation</h5>';
echo '<p>Search engine optimization (SEO), is the process of increasing website traffic from search engines. Search engine optimization targets non-paid traffic, also known as organic or natural results. It is not intended to target direct traffic or paid visitors. Search engine optimization can target unpaid traffic from different types of searches such as image, video, news, academic, and vertical search engines. Search engine optimization is an Internet marketing strategy that considers the way search engines work, how they behave, the computer-programmed algorithms which control search engine behavior, what people are searching for, the search terms and keywords used in search engines and which search engines are most preferred by their target audience. Because websites that rank higher in search engine results pages (SERP) will attract more traffic, search engine optimization is done. These visitors could then be converted into customers.</p>';
echo '</li>';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/digital-advertisement.webp">';
echo '</div>';
echo '<h5>Digital Ads</h5>';
echo '<p>Digital advertising is also known by the names of online marketing, internet advertising, online advertising and web advertising. It uses the Internet to promote products or services to users and audiences. Online advertising can include email marketing, social media marketing, search engine optimization (SEM), digital advertising, and many other types of display advertising, including web banner advertising. Programmatic advertising, which is a form of automated software that works across multiple sites, media services, and platforms, is gaining popularity. Online advertising is similar to other media. A publisher integrates ads into its online content and an advertiser provides the advertisements for display on the publisher's website. Advertising agencies that help create and place the advertising copy, an advertising server that technologically delivers the ads and tracks statistics, as well as advertising affiliates who perform independent promotional work for advertisers are all potential participants.</p>';
echo '</li>';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/content-creation.webp">';
echo '</div>';
echo '<h5>Content Creation</h5>';
echo '<p>Content creation refers to the sharing of information in any media, but especially digital media, for an end-user/audience within specific contexts. Content can be speech, writing, or any other medium that allows for self-expression, distribution and marketing, as well as publication. Content creation includes blogging, updating websites, writing articles, photography, videography and online commentary. Editing and distribution of digital media can also be done.</p>';
echo '</li>';
echo '<li class="four columns">';
echo '<div class="service-image">';
echo '<img src="images/services/ux-optimization.webp">';
echo '</div>';
echo '<h5>User Experience (UX) Research</h5>';
echo '<p>User experience research is the systematic study and analysis of target users and their needs to provide realistic contexts and insight to design processes. User experience researchers use a variety of methods to identify problems and design opportunities. They uncover valuable information that can be used to improve the design process.</p>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Quote';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="quote" class="quote featured-bg-image u-full-width">';
echo '<h4 class="centered">';
echo '<button class="button inverted">Get a quote now.</button>';
echo '</h4>';
echo '</section>';
echo '';
echo '<!-- Get in touch';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section id="contact" class="contact u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="twelve columns">';
echo '<h3 class="separator">Get in touch</h3>';
echo '<h4>Reach us to get a consultation.</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Contact';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section class="container contact-us u-full-width u-max-full-width">';
echo '<div class="row">';
echo '<div class="four columns contact-us-details">';
echo '<h3>Contact</h3>';
echo '<h5>';
echo 'Send message on WhatsApp by  <br />';
echo '+90 554 998 48 30<br />';
echo 'or send email to abgokhan@tacticus.digital <br />';
echo 'or fill the form.<br />';
echo '</h5>';
echo '<ul class="social-links">';
echo '<li>';
echo '<a href="http://twitter.com/abgoekhan" target="_blank">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="https://www.facebook.com/burakthedude" target="_blank">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="https://instagram.com/buraklebowski" target="_blank">';
echo '<i class="fa fa-instagram"></i>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a href="https://www.linkedin.com/in/abgokhan/" target="_blank">';
echo '<i class="fa fa-linkedin"></i>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="eight columns contact-us-form">';
echo '<form>';
echo '<div class="row">';
echo '<div class="six columns">';
echo '<input class="u-full-width" type="text" placeholder="Name" id="nameInput">';
echo '</div>';
echo '<div class="six columns">';
echo '<input class="u-full-width" type="email" placeholder="Email" id="emailInput">';
echo '</div>';
echo '</div>';
echo '<textarea class="u-full-width" placeholder="Message" id="messageInput"></textarea>';
echo '<input class="button u-pull-right" type="submit" value="Send">';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Footer';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '';
echo '<section class="footer u-full-width">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="twelve columns">';
echo '<h5>&copy 2022 tacticus.digital</h5>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- End Document';
echo '–––––––––––––––––––––––––––––––––––––––––––––––––– -->';
echo '</body>';
echo '</html>';
echo '';
?>